name: Main 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

   build_and_deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY_PATH: "DockerCICDExample"
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
   
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~\.nuget\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**\packages.lock.json') }}    

    - name: Restore dependencies
      run: cd DockerCICDExample/ && dotnet restore
      
    - name: Build
      run: cd DockerCICDExample/ && dotnet build --configuration Release --no-restore 
        
    - name: Dotnet publish
      run: dotnet publish 
          ${{ env.PROJECT_DIRECTORY_PATH }}/${{ env.PROJECT_DIRECTORY_PATH }}.csproj
          --configuration release -o testApp
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./DockerCICDExample/Dockerfile
          push: true
          tags: 23397/test:latest
  
